insert into products(item_code, item_name, brand_name, model_number, weight, dimension, description, category, quantity, price, imagename) values('HPPavillioni3', 'HP Pavillion Touch Smart 5th Gen i3','HP','Pavillion i3','5.34 lb','1.01 in (H) x 14.88 in (W) x 10.20 in (D)','This is the very light weight Notebook available at a very economic price', 'Laptop', 100, 500, 'images/HPPavillioni3.jpg'); 

insert into products(item_code, item_name, brand_name, model_number, weight, dimension, description, category, quantity, price, imagename) values('DELLINSPIRON3543', 'DELL INSPIRON 3543 W561034TH Intel Core i7 5th Generation','Dell','Dell Inspiron 3543','2.40 Kg','1 in (H) x 14 in (W) x 12 in (D)','This is one of the best Notebook in its class and is available at a very best price', 'Laptop', 100, 725, 'images/DELLINSPIRON3543.jpg'); 

insert into products(item_code, item_name, brand_name, model_number, weight, dimension, description, category, quantity, price, imagename) values('LenovoIdeapadG50', 'Lenovo Ideapad G50-80 5th Gen i5 12GB Ram 500GB Hdd Win8.1','Lenovo','Idea Pad G50-80','2.5 Kg','(W*D*H) 38.4 x 26.5 x 2.5cm','Amazing Notebook with classic features and remarkable performance is available at a very best price', 'Laptop', 100, 550, 'images/LenovoIdeapadG50.jpg'); 

insert into products(item_code, item_name, brand_name, model_number, weight, dimension, description, category, quantity, price, imagename) values('DellVostro153558', 'Dell Vostro 15 3558 Laptop (Intel Celeron- 4GB RAM- 500GB HDD- 39.62 cm (15.6)- Ubuntu Linux','Dell','Vostro 15 3558','2.25 Kg','(W*D*H) 381 x 267 x 25.6 mm','Dell brings to you this amazing Vostro 15 3558 Laptop to make your computing experience more interesting. Designed using Intel Celeron Dual Core Processor, 3205U variant, 2M Cache and 1.50 GHz Clock speed, the notebook delivers remarkable performance in each task that you throw at it. Further, the laptop is provided with Ubuntu Linux 14.04 SP1 operating system to deliver users a secure working platform.', 'Laptop', 100, 325, 'images/DellVostro153558.jpg'); 

insert into products(item_code, item_name, brand_name, model_number, weight, dimension, description, category, quantity, price, imagename) values('AsusX200CA-KX219D', 'Asus X200CA-KX219D Laptop (3rd Gen Intel Core i3 3217U- 4GB RAM- 500GB HDD- 29.46cm','Asus','X200CA KX219 D','1.2 kg','(W*D*H) 302 x 200 x 30.4 mm  ','Asus laptops are known to add vibrancy to computing be it for everyday use or professional use. This Asus X200CA-KX219D Laptop comes in portable design and a beautiful white hue. Powered by 3rd Generation Intel Core i3 3217U processor, the laptop offers smooth responsive computing to give you a device that is geared for everyday tasks or multimedia entertainment. Take the entertainment to the next level with its 29.46cm (11.6) HD TFT LCD glare display with LED backlit. Further, the laptop comes with two USB 2.0 ports, one USB 3.0 port and one HDMI Port adding more power to the whole package.', 'Laptop', 100, 665, 'images/AsusX200CAKX219D.jpg'); 

insert into products(item_code, item_name, brand_name, model_number, weight, dimension, description, category, quantity, price, imagename) values('Apple(MGX92HN/A)', 'Apple (MGX92HN/A) MacBook Pro Notebook (4th Gen Intel Core i5- 8GB RAM- 512GB SSD- 33.78cm (13.3)- Mac OS X Mavericks)','Apple','MGX92HN/A MacBook Pro','1 kg','(W*D*H) 302 x 200 x 30.4 mm','Designed to meet your computing needs, this Apple MGX92HN/A MacBook Pro Notebook is a must-have for everyday use. It is powered by Intel Core i5 Processor with a clock speed of 2.8 GHz (Turbo Boost of up to 3.3 GHz) and 3 MB cache memory, which make sure you enjoy fast and efficient performance. The laptop is loaded with Mac OS X Mavericks, which promises a plethora of applications that are entertaining, interesting and engaging. The included software encompasses iPhoto, iMovie, GarageBand, Pages, Numbers, Keynote, Maps, iBooks, Safari, Mail, FaceTime, Messages, Calendar, Contacts, Reminders, Time Machine, Photo Booth, iTunes, Game Center, Preview, Notes, Mac App Store.', 'Laptop', 100, 2000, 'images/AppleMGX92HNA.jpg'); 

insert into products(item_code, item_name, brand_name, model_number, weight, dimension, description, category, quantity, price, imagename) values('HPProbook6570', 'HP Probook 6570b D0M83PAACJ (Intel Core i5 3210M- 4GB RAM- 500 GB HDD- 35.56cm (14)- Win8 Pro','HP','Probook 6570b','2.51 kg','(W*D*H) 14.72 x 9.86 x 1.35 in','Designed to meet your computing needs, the HP Probook 6570b D0M83PAACJ is a must-have for students as well as professionals. It is powered by (third generation) Intel Core i5-3210M processor with a clock speed of 2.5 GHz that goes up to 3.1 GHz and 3 MB L3 cache memory, which make sure you enjoy fast and efficient performance. The laptop is loaded with Windows 8 Professional 64-bit operating system, which promises a plethora of applications that are entertaining, interesting and engaging.', 'Laptop', 100, 825, 'images/HPProbook6570.jpg'); 

insert into products(item_code, item_name, brand_name, model_number, weight, dimension, description, category, quantity, price, imagename) values('ToshibaC50a-P0015', 'Toshiba C50a-P0015 Laptop (Intel Pentium N3520- 2GB RAM- 500GB HDD- 39.62cm (15.6)- DOS)','Toshiba','C50a-P0015','2.3 Kg','(W*D*H) 380 x 242 x 33.32 mm','With the all new Toshiba Satellite C50-A P0015 15.6-inch Laptop, you can enjoy premium quality sight and sound, and hassle free execution of your entire task. Toshiba is known to provide users with products that are of the highest grade and this 15.6 inches laptop is no different. This efficient everyday laptop is packed with features that not only increase the usability of the product but also makes work for the users much simpler. This Toshiba Laptop guarantees to deliver performance, style and convenience. So, before you go ahead and shop online for this versatile laptop, take a quick look at all the special features that this device has to offer.', 'Laptop', 100, 450, 'images/ToshibaC50aP0015.jpg'); 

insert into products(item_code, item_name, brand_name, model_number, weight, dimension, description, category, quantity, price, imagename) values('XPERIAT3WHITE', 'Sony XPERIA T3 (White) 5.3" 8MP Quad Core Android 4.4 WiFi 3G Phone','Sony','C50a-P0015','130g','(W*D*H) 380 x 242 x 33.32 mm','Encased in a stainless steel frame, the slim and stylish sony xperia T3 smartphone is ready to amaze you with its excellent features. Equipped with a bright TRILUMINOUS display, the smartphone makes your videos come alive. Powered by the latest processor along with an advanced operating system, the Sony smartphone thrills you with seamless multitasking and smooth operating experience. The excellent storage capacity of the smartphone allows you to store all your important files, images and more in the smartphone without facing any space crunch.', 'CellPhone', 100, 230, 'images/XperiaT3White.jpg'); 

insert into products(item_code, item_name, brand_name, model_number, weight, dimension, description, category, quantity, price, imagename) values('MicromaxKnight2E471', 'Micromax-Canvas-Knight-2-E471-White','Micromax','Canvas Knight 2 E471 White','120g','(W*D*H) 380 x 242 x 33.32 mm','It is a 5” handset sporting HD Amoled Display. With a screen protection from Corning Gorilla Glass 3, it measures 142X72X6.3mm in dimension. It has a glass body with a metal chasing to give it smart and alluring look. It just measures 6.3mm in thickness which gives it quite sleek look. It has a 5” display which is easy to carry and large enough to let users enjoy the movies, videos, etc.', 'CellPhone', 100, 210, 'images/MicromaxKnight2E471.jpg'); 

insert into products(item_code, item_name, brand_name, model_number, weight, dimension, description, category, quantity, price, imagename) values('SonyXperiaE4Dual', 'Sony Xperia E4 Dual - 8 GB - White - Smartphone','Sony','E4 Dual','144 g','Height 13.7 cm, Width 7.5 cm, Depth 1.05 cm','Encased in an extremely stylish design along with Sony’s legendary expertise, the all-new Sony Xperia E4 smartphone will certainly impress you with its outstanding performance. Access internet, listen to high-octane music and stay up-to-date with what’s happening around you with Sony Xperia smartphone. Power packed with the latest processor along with the advanced operating system (OS), the Sony smartphone facilitates you with seamless multitasking and smooth operating experience. Additionally, the astounding battery performance of the smartphone makes it more reliable and user-friendly.', 'CellPhone', 100, 130, 'images/SonyXperiaE4Dual.jpg'); 

insert into products(item_code, item_name, brand_name, model_number, weight, dimension, description, category, quantity, price, imagename) values('AppleiPhone4s', 'Apple iPhone 4s - 8 GB - Black - Smartphone','Apple','4s','140 g','Height - 11.43 cm, Depth - 0.94 cm','Stylish and elegant, this black Apple iPhone 4s cell phone features built in Wi-Fi, allowing you to interact, browse, and download every time you want, no matter where you are. The smartphone runs on the powerful iOS operating system and is empowered by a 1 GHz dual core Cortex-A8 processor, making multitasking easy. Plus, the Apple iPhone comes with SMS and MMS messaging, as well as email, push mail, and instant messaging capabilities.', 'CellPhone', 100, 220, 'images/AppleiPhone4s.jpg'); 

insert into products(item_code, item_name, brand_name, model_number, weight, dimension, description, category, quantity, price, imagename) values('LenovoS850', 'Lenovo S850 16GB White','Lenovo','S850','140 g','HxWxD 141 x 71 x 8.2 mm','Designed with advanced features along with a stylish look, the new Lenovo S850 smartphone is ready to amaze you with its excellent performance. Equipped with the latest MTK 6582 1.3 GHz Quad-core PowerVR SGX544 processor along with the new Android™ 4.4.2 KitKat Operating System (OS), this outstanding smartphone facilitates you with seamless multitasking and smooth operating experience. Watch your favourite videos and play graphic intensive games on a bright 12.7 cm (5) capacitive touchscreen of the Lenovo smartphone. With its 16 GB ROM, you can easily store all your important files, images, videos and more in the smartphone for quick and easy access. Click stunning snapshots with the 13 MP primary camera of the Lenovo smartphone that clicks every image with superb clarity and rich image details.', 'CellPhone', 100, 150, 'images/LenovoS850.jpg'); 

insert into products(item_code, item_name, brand_name, model_number, weight, dimension, description, category, quantity, price, imagename) values('MicromaxCanvasPep8', 'Micromax Canvas Pep 8GB Blue','Micromax','Canvas Pep Q371','140 g','HxWxD 133.5 x 66.5 x 9.8mm','Micromax Canvas Pep Q371 Smart Mobile Phone – Blue is the latest phone from Micromax that comes with Dual SIM slots and a wide display of 11.43 cm (4.5). It comes with the latest Android 4.4.2 Kitkat Operating System. It is built-in with the fastest 1.3 GHz Quad-core processor. This phone comes with the latest Android 4.4.2 Kitkat Operating System. Its 5MP rear and 0.3MP front camera lets you click clearer pictures. In order to give you the best connectivity this 3G smart phone comes with Wi-Fi, USB and Bluetooth. It is built-in with 1GB RAM and the storage capacity is 8GB internal and up to 32GB expandable with a microSD card. Also, it has a powerful battery of 1700 mAh that gives you long duration of talk-time.', 'CellPhone', 100, 85, 'images/MicromaxCanvasPep8.jpg'); 

insert into products(item_code, item_name, brand_name, model_number, weight, dimension, description, category, quantity, price, imagename) values('LenovoA5000', 'Lenovo A5000 8GB White','Lenovo','A5000','160 g','HxWxD 140 x 71.4 x 10 mm','The Lenovo A5000 comes with an 1.3GHz quad-core processor and is accompanied by 1GB RAM. The A5000 runs on Android 4.4.2 KitKat and also comes with the ability to handle two SIM cards at once. Lenovo has made no announcement regarding the availability of Android 5.0 Lollipop update for A5000, though we feel it would be available for the said smartphone. The Lenovo A5000 sports a screen measuring 5 inches across and it puts out display resolution of 1280x720 pixels. The A5000 sports 8GB internal storage capacity and it can be expanded further up to 32GB with the use of a microSD card.', 'CellPhone', 100, 130, 'images/LenovoA5000.jpg'); 

insert into products(item_code, item_name, brand_name, model_number, weight, dimension, description, category, quantity, price, imagename) values('iPhone664', 'iPhone 6 64 GB','Apple','iPhone 6','129 g','HxWxD 138.1 x 67 x 6.9 mm','Apple iPhone 6 exudes elegance and excellence at its best. With iOS 8, the world’s most advanced mobile operating system, and a larger and superior 4.7 inches high definition Retina display screen, this device surpasses any expectations you might have with a mobile phone. Apple iPhone 6 includes a revolutionary NFC Apply Pay Wallet which functions like a credit card. You can shop in the stores or buy stuff online in a secure, private and easy way with a single touch on your iPhone 6 using Apple Pay Wallet.', 'CellPhone', 100, 1750, 'images/iPhone664.jpg'); 

insert into products(item_code, item_name, brand_name, model_number, weight, dimension, description, category, quantity, price, imagename) values('MicrosoftLumia640XL', 'Microsoft Lumia 640 XL Dual SIM 8GB','Microsoft','Lumia 640 XL','171 g','HxWxD 15.79 x 8.15 x 0.9 cm','Take your multimedia experience a notch higher with the all new Microsoft Lumia 640 XL Dual SIM smartphone.  Specially designed to meet your active lifestyle and business requirements, this ultimate smartphone makes your everyday tasks smooth and more interesting. Organize high quality video calls on Skype, track your ideas on OneNote, click beautiful pictures and keep a balance between your work and Play with the high performance smartphone brought to you by Microsoft. Power packed with the latest processor along with an advanced operating system, the Microsoft Lumia smartphone facilitates you with seamless multitasking and smooth operating experience.', 'CellPhone', 100, 230, 'images/MicrosoftLumia640XL.jpg'); 

insert into productfeatures(item_code, feature1, feature2, feature3, feature4, feature5, feature6) values('HPPavillioni3', '8GB Ram', 'Hard Drive Capacity: 750 GB', 'Screen Size: 15.6"','Graphic Card: 2GB, Intel HD Graphics 5500 Graphics Processing', 'Operating System: Windows 8.1','Touch Memory: 8 GB');   

insert into productfeatures(item_code, feature1, feature2, feature3, feature4, feature5, feature6) values('DELLINSPIRON3543', 'Operating System: Ubuntu', 'Graphic Card: 2 GB Processor Speed: 2.40 GHz', 'Screen Size:  15.6"','Processor: Intel Core i7 (5th Generation)', 'Memory: 8 GB','Hard Drive Capacity: 1 TB');   

insert into productfeatures(item_code, feature1, feature2, feature3, feature4, feature5, feature6) values('LenovoIdeapadG50', 'Operating System:  Windows 8.1', 'Processor: Intel Core i5 (5th Generation)', 'Memory: 12 GB','Hard Drive Capacity: 500 GB', 'Screen Size: 15.6"','Integrated Graphics Memory Capacity 1.5GB');   

insert into productfeatures(item_code, feature1, feature2, feature3, feature4, feature5, feature6) values('DellVostro153558', 'Operating System : Linux/Ubuntu', 'Hard Disk Capacity : 500 GB', 'Memory (Ram) : 4 GB','8x DVD+/-RW 9.5mm Optical Disk Drive', 'Screen Size : 39.62cm (15.6)','Processor : Celeron Dual Core (5th Generation)');  

insert into productfeatures(item_code, feature1, feature2, feature3, feature4, feature5, feature6) values('AsusX200CA-KX219D', 'Built-in Speakers with Sonic Master Audio Technology', '4 GB DDR3 RAM', '500 GB Hard Disk Capacity','3rd Generation Intel Core i3-3217U Processor', ' 29.46cm (11.6) HD TFT LCD Glare Display with LED Backlit','Chiclet Keyboard');    

insert into productfeatures(item_code, feature1, feature2, feature3, feature4, feature5, feature6) values('Apple(MGX92HN/A)', 'Processor : Core i5 (4th Generation)', 'Screen Size : 33.78cm (13.3)', '13.3-inch LED backlit retina display with IPS technology','Memory (Ram) : 8 GB', 'Hard Disk Capacity : 512 GB','Operating System : Mac OS X');   

insert into productfeatures(item_code, feature1, feature2, feature3, feature4, feature5, feature6) values('HPProbook6570', 'RAM: 4 GB', 'Hard Disk Capacity: 500 GB', 'Processor Name: Intel Core i5-3210M','Keyboard: Full-size, Spill-resistant Keyboard with Drains', 'Screen Size: 35.56cm (14)','Speakers: Integrated Stereo Speakers');   

insert into productfeatures(item_code, feature1, feature2, feature3, feature4, feature5, feature6) values('ToshibaC50a-P0015', 'Hard Disk Capacity : 500 GB', 'Operating System : DOS', 'Screen Size : 39.62cm (15.6)','Processor : Pentium Quad Core (3rd Generation)', 'Memory (Ram) : 2 GB','Magnificent HD LED backlit clear super view screen with the resolution of 1,366 x 768 pixels'); 

insert into productfeatures(item_code, feature1, feature2, feature3, feature4, feature5, feature6) values('XPERIAT3WHITE', '1.4 GHz Qualcomm Snapdragon MSM8228 Quad Core Processor', 'Operating System:  Android v4.4 (KitKat) OS', '8 MP Primary Camera, 1.1 MP Secondary Camera','5.3-inch Touchscreen', 'Expandable Storage Capacity of 32 GB','Wi-Fi Enabled');  

insert into productfeatures(item_code, feature1, feature2, feature3, feature4, feature5, feature6) values('MicromaxKnight2E471', 'OS: Android OS, v5.0 (Lollipop)', 'CPU:Octa-core 1.5 GHz', 'RAM:2 GB RAM, Internal Memory:16 GB','Camera:13 MP, 4128 x 3096 pixels, autofocus, dual-LED flash', 'Battery Capacity:Non-removable Li-Ion 2260 mAh battery','Standby Time : Up to 335 h (3G), Talktime : Up to 7 h 45 min (3G)');   

insert into productfeatures(item_code, feature1, feature2, feature3, feature4, feature5, feature6) values('SonyXperiaE4Dual', 'Capacity: 8 GB', 'Screen Size: 5 in.', 'Operating System: Android','Battery Life: Up to 12.75 hr', 'Camera: 5.0 MP','Display Size: 540 x 960');   

insert into productfeatures(item_code, feature1, feature2, feature3, feature4, feature5, feature6) values('AppleiPhone4s', 'Capacity: 8 GB', 'Screen Size - 3.5 in, Display Size - 640 x 960', 'Operating System - iPhone OS 4 (iOS 4)','Battery Life - Up to 14 hr, Standby Battery Life - Up to 200 hr', 'Processor Speed - 1 MHz','Camera - 8.0 MP');   

insert into productfeatures(item_code, feature1, feature2, feature3, feature4, feature5, feature6) values('LenovoS850', 'Android 4.4.2 KitKat', '13 MP Rear Camera, 5 MP Front Camera', '1 GB RAM, 16 GB ROM','Screen Size : 12.7 cm (5) display', 'Display Resolution 720 x 1280 pixels','Battery Capacity 2000 mAh, Talk Time Up to 13 h, Standby Time Up to 336 h');   

insert into productfeatures(item_code, feature1, feature2, feature3, feature4, feature5, feature6) values('MicromaxCanvasPep8', 'Android 4.4.2 KitKat', '1.3GHz Quad Core', '1 GB RAM / 8 GB ROM','5MP Rear Camera, 0.3MP Front Camera', '1700mAh Battery, Talk Time Up to 6 h (3G), Standby Time Up to 210 h (3G)','Screen Size: 11.4 cm (4.5), Display Resolution 854 x 480 pixels');   

insert into productfeatures(item_code, feature1, feature2, feature3, feature4, feature5, feature6) values('LenovoA5000', 'OS Version : Android OS, v4.4.2 (KitKat)', 'Processor Speed : 1.3 GHz', 'Front Camera : 2MP to 4.9MP, Rear Camera : 8MP to 9.9MP','RAM : 1 GB, Internal Memory : 8GB, User Memory 4GB, Expandable Memory 32 GB', 'Screen Size (in cm) 12.7 (5), Display Resolution 720x1280 pixel','Battery 4000 mAh Capacity, 768 hrs Stand by Time, 30 hrs Talk Time'); 

insert into productfeatures(item_code, feature1, feature2, feature3, feature4, feature5, feature6) values('iPhone664', 'OS Version iOS 8', 'Screen Size (in cm): 11.9 cm (4.7), Display Resolution 750 x 1334 pixels', 'Processor Speed: 1.4 GHz','RAM: 1 GB, Internal Memory: 64 GB', 'Front Camera: 1.2 MP, Rear Camera: 8 MP','Battery Capacity 1810 mAh, Talk Time Up to 14 h, Standby Time Up to 250 h');   

insert into productfeatures(item_code, feature1, feature2, feature3, feature4, feature5, feature6) values('MicrosoftLumia640XL', 'OS: Microsoft Windows Phone 8.1 with Lumia Denim', '14.47 cm (5.7) IPS LCD Display, Display Resolution 1280 x 720 pixels', 'Quad-core 1.2 GHz Processor','1 GB RAM and 8 GB ROM, Upto 128 Gb Extensible Memory', '13 MP Rear Camera and 5 MP Front Camera','Li-Ion 3000 mAh battery, Talk Time Up to 31 h 20 min (2G) / Up to 23 h 40 min (3G)');   



